### ISSUE TITLE
Feature Request inTransaction

### ISSUE THREAD

**Issue by moreamazingnick** [Icinga/ipl-sql#83] opened 2024-03-14 12:22 UTC
It would be really nice to have a function inTransaction in Connection.php for more complex structures. PDO supports this
```php
    /**
     * Begin a transaction
     *
     * @return bool Whether the a transaction was previously requested
     */
    public function beginTransaction()
    {
        if ($this->pdo === null) {
               return false;
        }else{
               return $this->pdo->inTransaction();
        }

    }
```

thanks in advance and 

best Regards 
Nicolas

**Comment by nilmerg** [comment] 2024-03-14 14:01
Duplicate of #81

**Closed by nilmerg** 2024-03-14 14:01 UTC
